### ISSUE TITLE
[Question] I run the original code but unexpectedly get result 0%

### ISSUE THREAD

**Issue by palelaughing** [rutgerswiselab/GenRec#1]
![exp records](https://github.com/palelaughing/pic-repositry/blob/main/genrec%20exp%20records%201.png?raw=true)

how can I get a normal result?

**Comment by zhhhzhang** [comment]
the same error, do you know why?

**Comment by jianchaoji** [comment]
> ![exp records](https://github.com/palelaughing/pic-repositry/blob/main/genrec%20exp%20records%201.png?raw=true)
> 
> how can I get a normal result?
What is the size of your LoRA adapter? I mean the lora_adapter.bin file.
