### ISSUE TITLE
评估结果不理想

### ISSUE THREAD

**Issue by fine1123** [rutgerswiselab/GenRec#3]
您好作者。我复现您提供的代码，发现评估结果并不是很理想，是否数据集太小，您能否提供一下完整的数据集。谢谢！

**Comment by jianchaoji** [comment]
数据集是完整的。有可能是训练过程中adapter没弄好。具体可参考https://github.com/rutgerswiselab/GenRec/issues/2#issuecomment-1807346237

**Comment by fine1123** [comment]
感谢您的回复！
