### ISSUE TITLE
How to make input data?

### ISSUE THREAD

**Issue by Jiseok-Yang** [rutgerswiselab/GenRec#4]
Hello, I was very impressed by your GenRec paper. In the paper, you mentioned using the most recent data as test data and the second most recent data as validation data. Is there a separate code to generate this data?

**Comment by ElvinJi** [comment]
Hello, due to the varying formats of different datasets, we do not provide code to generate the data. However, the main idea is to transform the user's historical behavior data into a sequence, leaving the last item as the test.
