### ISSUE TITLE
关于movies数据集大小的问题

### ISSUE THREAD

**Issue by shh924** [rutgerswiselab/GenRec#5]
发现toys数据集的训练集与测试集的大小是10:1，然而movies数据集训练集与测试集的大小是1:1,麻烦作者检查下是不是没上传完整的movies训练集，这可能导致了movies在我这里跑出来的结果和论文上的结果有差别

**Comment by jianchaoji** [comment]
这个是完整的数据集
https://drive.google.com/drive/folders/1-aDc37UzocGD52WFLH2BaJs0hQw8GWcg?usp=drive_link

**Comment by shh924** [comment]
> 这个是完整的数据集 https://drive.google.com/drive/folders/1-aDc37UzocGD52WFLH2BaJs0hQw8GWcg?usp=drive_link

谢谢！
