### ISSUE TITLE
URL missing

### ISSUE THREAD

**Issue by cuju666** [rutgerswiselab/GenRec#6]
When the program is run, the following error is displayed:
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/decapoda-research/llama-7b-hf/resolve/main/config.json

**Comment by jianchaoji** [comment]
This is because the llama-7b-hf is no more supported. You can replace the backbone to some other models. Like other models under https://huggingface.co/decapoda-research
